import cv2 
import numpy as np
import matplotlib.pyplot as plt

I=cv2.imread(r'C:\Users\adshi\Pictures\Saved Pictures\obama.jpg')
b,g,r=cv2.split(I)
image_read_color_pyplot=cv2.merge([r,g,b])
j=cv2.resize(image_read_color_pyplot,(1000,500))
l=cv2.imread(r'C:\Users\adshi\Pictures\Saved Pictures\download.jfif')
b,g,r=cv2.split(l)
image_read_color_pyplot1=cv2.merge([r,g,b])
k=cv2.resize(image_read_color_pyplot1,(1000,500))
sumimg=cv2.add(j,k)
subimg=cv2.subtract(j,k)
andimg=cv2.bitwise_and(j,k)
orimg=cv2.bitwise_or(j,k)
notimg=cv2.bitwise_not(j)
xorimg=cv2.bitwise_xor(j,k)
plt.subplot(2,3,1); plt.title("Addition")
plt.imshow(sumimg)
plt.subplot(2,3,2); plt.title("Subtraction")
plt.imshow(subimg)
plt.subplot(2,3,3); plt.title("AND logic image")
plt.imshow(andimg)
plt.subplot(2,3,4); plt.title("OR logic image")
plt.imshow(orimg)
plt.subplot(2,3,5); plt.title("NOT logic image")
plt.imshow(notimg)
plt.subplot(2,3,6); plt.title("XOR logic image")
plt.imshow(xorimg)
plt.show()