webtalk_init -webtalk_dir D:/Academic stuff/MSIS Github/Programming-practice/ACA Verilog/Moore machine/moore_seq_10110/moore_seq_10110.sim/sim_1/behav/xsim/xsim.dir/moore_10110_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan 12 20:04:30 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b05c2998-02e2-4d7d-9015-59305d8e82cc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a1c8da478f894e7d86f7e1f04372d559" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "2" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "66 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "2 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "12" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.30_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "41164_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1198654375 -regid "" -xml D:/Academic stuff/MSIS Github/Programming-practice/ACA Verilog/Moore machine/moore_seq_10110/moore_seq_10110.sim/sim_1/behav/xsim/xsim.dir/moore_10110_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Academic stuff/MSIS Github/Programming-practice/ACA Verilog/Moore machine/moore_seq_10110/moore_seq_10110.sim/sim_1/behav/xsim/xsim.dir/moore_10110_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Academic stuff/MSIS Github/Programming-practice/ACA Verilog/Moore machine/moore_seq_10110/moore_seq_10110.sim/sim_1/behav/xsim/xsim.dir/moore_10110_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
